import "@/styles/globals.css";
import { ConfigProvider, App } from "antd";
import type { AppProps } from "next/app";
import type { Metadata } from "next";
import theme from "../theme/themeConfig";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
import localFont from "next/font/local";
const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/Poppins/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins/Poppins-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/Poppins/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Poppins/Poppins-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-poppins", // Custom CSS Variable
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Page({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    <ConfigProvider theme={theme}>
      <App>
        <Head>
          <title>Synapsis Blog</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <main className={poppins.variable}>
          <QueryClientProvider client={queryClient}>
            <Component {...pageProps} />
          </QueryClientProvider>
        </main>
      </App>
    </ConfigProvider>
  );
}
