import "@/styles/globals.css";
import { ConfigProvider } from "antd";
import type { AppProps } from "next/app";
import type { Metadata } from "next";
import theme from "../theme/themeConfig";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import { Poppins } from "next/font/google";
// const poppins = Poppins({
//   weight: ["400", "700"],
//   style: ["normal", "italic"],
//   subsets: ["latin"],
//   display: "swap",
// });
// console.log(poppins.className);
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function App({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    // <ConfigProvider theme={theme}>
    // </ConfigProvider>
      <QueryClientProvider client={queryClient}>
        {/* <main className={poppins.className}>
        </main> */}
          <Component {...pageProps} />
      </QueryClientProvider>
  );
}
